name: 'flutter_tracker'
description: 'A Family Tracker for Flutter'
version: '1.0.0+44'

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter:
    sdk: 'flutter'

  cupertino_icons: '^0.1.3'
  firebase_auth: '0.15.3'
  firebase_messaging: '6.0.9'
  firebase_remote_config: '^0.3.0+1'
  cloud_firestore: '^0.13.0+1'
  google_sign_in: '^4.1.1'
  flutter_map: '^0.8.2'
  redux: '^4.0.0'
  flutter_redux: '^0.6.0'
  redux_epics: '^0.13.0'
  rxdart: '^0.23.1'
  flutter_background_geolocation: '^1.7.0'
  flutter_native_timezone: '^1.0.4'
  screen: '^0.0.5'
  share: '^0.6.3+5'
  sliding_up_panel: '^1.0.0'
  intl: '^0.16.1'
  flushbar: '^1.9.1'
  rflutter_alert: '^1.0.3'
  simple_animations: '^1.3.6'
  timeago_flutter: '^0.1.0'
  package_info: '^0.4.0+13'
  device_info: '^0.4.1+4'
  camera: '^0.5.7+3'
  image_picker: '^0.6.3+1'
  connectivity: '^0.4.6+2'
  battery: '^0.3.1+7'
  path_provider: '^1.6.0'
  crypto: '^2.1.3'
  transformer_page_view: '^0.1.6'
  latlong: '^0.6.1'
  in_app_purchase: '^0.3.0+2'
  admob_flutter: '^0.3.4'
  webview_flutter: '^0.3.19+5'
  date_range_picker: '^1.0.6'
  pimp_my_button: '^1.0.0'
  retry: '^3.0.0+1'
  location_permissions: '^2.0.4+1'
  flutter_slidable: '^0.5.4'
  cached_network_image: '^2.0.0'
  flutter_compass: '^0.3.6'
  sticky_headers: '^0.1.8+1'
  logger: '^0.8.3'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - 'assets/flutter_tracker-icon.png'
    - 'assets/flutter_tracker-logo.png'
    - 'assets/flutter_tracker-logo-shadow.png'